{
 "title": "Ethereum Deposit Tracker",
 "time": { "from": "2024-09-10T06:30:00.000Z", "to": "2024-09-10T10:30:00.000Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Real-Time Ethereum Deposit Tracker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Number of Deposits Tracked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) AS \"No. of deposits tracked\" FROM deposits LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fee Details",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(fee) AS \"Average Fee\", MIN(fee) AS \"Min Fee\", MAX(fee) AS \"Max Fee\" FROM deposits LIMIT 50 "
    }
   ]
  },
  {
   "title": "Deposit Volume over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    DATE_TRUNC('hour', to_timestamp(\"blockTimestamp\")) AS hour,\r\n    COUNT(*) AS deposit_count,\r\n    SUM(fee) AS total_deposit_value\r\nFROM\r\n    deposits\r\nGROUP BY\r\n    hour\r\nORDER BY\r\n    hour ASC;"
    }
   ]
  },
  {
   "title": "Latest Deposit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"blockNumber\", \"blockTimestamp\", fee\r\nFROM deposits\r\nORDER BY \"blockTimestamp\" DESC\r\nLIMIT 1;\r\n"
    }
   ]
  }
 ]
}